### ISSUE TITLE
More integer conversions causing data to return all 0's

### ISSUE THREAD

**Issue by jkope892** [PatrickChodowski/NBAr#6]
Conversions from double to integer causing all data in player season usage tables (get_general("player", measure_type = "usage") ) to return all 0's .  If I may , I would probably suggest to just let it return numbers as double and remove the  integer conversions and leave it up to the users to convert on the front end if they wish.  It would just save you a great deal of headaches.

Otherwise, still loving the package!  By far the best NBA api wrapper in R.

**Comment by PatrickChodowski** [comment]
Hi, I removed the conversion to int completely, hopefully this helps and doesnt break anything
